### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by lui75** [FelixFrog/pdfgrabber#1]
Ciao Francesco, ho appena scaricato il tuo script su consiglio di un altro sviluppatore github, ma lanciandolo ottengo un syntax error e il programma si blocca. Uso piattaforma macOS 12.6.

luigi@George pdfgrabber-master % python3 main.py                     
  File "/Users/luigi/Documents/pdfgrabber-master/main.py", line 151
    match action:
          ^
SyntaxError: invalid syntax
luigi@George pdfgrabber-master % 

Grazie per l'aiuto.

**Comment by FelixFrog** [comment]
Ciao! Il requisito minimo è python3.10. Prova ad aggiornarlo con ```brew upgrade python``` (oppure prova ```brew install python@3.10``` se non funziona ed eseguilo con ```python3.10 main.py````)

**Comment by FelixFrog** [comment]
Con e68b697bf1cefd4ef8febca14752b52cb8c62dee ora dovrebbe dare un errore più specifico. Grazie di aver segnalato.

**Comment by lui75** [comment]
Fatto. ora ho questo errore al lancio dello script.

igi@George ~ % python3 --version
Python 3.10.8
luigi@George ~ % cd /Users/luigi/Documents/pdfgrabber-master 
luigi@George pdfgrabber-master % python3 main.py                             
Traceback (most recent call last):
  File "/Users/luigi/Documents/pdfgrabber-master/main.py", line 1, in <module>
    import utils
  File "/Users/luigi/Documents/pdfgrabber-master/utils.py", line 2, in <module>
    import fitz
ModuleNotFoundError: No module named 'fitz'

**Comment by lui75** [comment]
Ho fatto di nuovo tutto da capo. aggiornato pip. ora funziona. Grazie.
