### ISSUE TITLE
errore quando apro il file

### ISSUE THREAD

**Issue by asiazzz** [FelixFrog/pdfgrabber#104]
Ho installato tutto quello che c'era in requirements.txt
Mi dà questo errore non appena apro main.py ...  pure un altra persona aveva avuto questo problema ed era stato risolto ma ora non funziona più

Could not find platform independent libraries <prefix>
Traceback (most recent call last):
  File "C:\Users\rubia\Desktop\pdfgrabber-master\main.py", line 1, in <module>
    import utils
  File "C:\Users\rubia\Desktop\pdfgrabber-master\utils.py", line 2, in <module>
    import fitz
ModuleNotFoundError: No module named 'fitz'

**Comment by FelixFrog** [comment]
Ciao. Prova a scaricare l'ultima versione (aggiornata 13 secondi fa) e ad eseguire `py -m pip install --upgrade -r requirements.txt`
Fammi sapere se funziona o se ti da un nuovo errore

**Comment by asiazzz** [comment]
perfetto funziona tutto grazie mille

**Comment by sefirothmorpheus** [comment]
su alcuni libri escono i seguenti errori:

MuPDF error: syntax error: unknown colorspace: Black

MuPDF error: syntax error: unknown colorspace: Black

Saving pdfMuPDF error: syntax error: unknown colorspace: Black

MuPDF error: syntax error: unknown colorspace: All

MuPDF error: syntax error: unknown colorspace: All
