### ISSUE TITLE
Sanoma disappearance

### ISSUE THREAD

**Issue by martadove** [FelixFrog/pdfgrabber#106]
Hello,
I see from your table in the description box  the Snm download is apparently implemented (and I definitely remember using it in the past), but now when I open the repo it is not present. What have I done wrong?
![snm](https://github.com/user-attachments/assets/f82a0529-1e20-424d-9f4c-9b35b3d8f8f9)

**Comment by FelixFrog** [comment]
Try to download it again, making sure you are using the latest commit
