### ISSUE TITLE
kitaboo oneshot

### ISSUE THREAD

**Issue by dani9099** [FelixFrog/pdfgrabber#11]
ciao, innanzitutto grazie mille per questo tool!

Ho un problema con kitaboo., una volta incollato il link nel formato https://my.zanichelli.it/kitaboo/8de675b4d3b9a9ba1cd08eac93f65530 ad esempio, ottengo questo errore
---
Kitaboo url: https://my.zanichelli.it/kitaboo/8de675b4d3b9a9ba1cd08eac93f65530
Starting... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
Traceback (most recent call last):
  File "/Users/dani/Desktop/pdfgrabber-master/main.py", line 222, in <module>
    main()
  File "/Users/dani/Desktop/pdfgrabber-master/main.py", line 206, in main
    downloadoneshot()
  File "/Users/dani/Desktop/pdfgrabber-master/main.py", line 160, in downloadoneshot
    pdfpath = utils.downloadoneshot(service, url, progressfun)
  File "/Users/dani/Desktop/pdfgrabber-master/utils.py", line 53, in downloadoneshot
    result = service.downloadbook(url, progress)
  File "/Users/dani/Desktop/pdfgrabber-master/services/oneshot/ktb.py", line 25, in downloadbook
    usertoken = tokenvalidation["userToken"]
KeyError: 'userToken'

ho letto che il file ktb.py è ancora in via di sviluppo ma, perlomeno con il mio libro, il formato delle pagine è in xhtml non in svg
lo schema dell'url è il seguente
"https://webreader.zanichelli.it/ContentServer/mvc/s3view/1568472/fixed_epub_image/1568472/OEBPS/Text/Parte01.xhtml"
e le immagini qui presenti sono a loro volta contenute a loro volta in pagine xhtml.

ho provato per lo stesso libro un altro script su github (in cui avevo aperto una segnalazione) https://github.com/Leone25/kitaboo-downloader che svolge lo stesso compito ma purtroppo non ha funzionato

**Comment by FelixFrog** [comment]
Ciao! Sono a conoscenza del tuo problema. Purtroppo il fatto di renderizzare solo gli sfondi svgz era una scorciatoia e non la soluzione definitiva, che in generale funziona per la maggior parte dei libri kitaboo. Il tuo libro invece è un libro possiamo dire "liquido", ossia che non ha una struttura paginata ben definita. Questo necessita un approccio molto diverso, poiché l'impaginazione, i font e tutto quanto dipendono dal browser. 

Non penso che la possibilità di scaricare questi libri in modo automatico verrà aggiunta in un futuro molto prossimo, perché richiede una quantità di lavoro non indifferente. Una cosa che ti consiglio di fare è usare pdfgrabber facendo il login sul servizio znc con username e password che possiedono questo libro e provare da lì.

In ogni caso ti posso suggerire un workaround intorno all'interfaccia scomoda di kitaboo:

1. Apri il link kitaboo. Assicurati che la pagina sia completamente caricata. Questo imposterà i cookie necessari per accedere al libro.
2. Visita [questo link](https://webreader.zanichelli.it/ContentServer/mvc/s3view/1568472/fixed_epub_image/1568472/OEBPS/Text/nav.xhtml). Qui puoi navigare le pagine xhtml del libro dal tuo browser, senza doverle vedere come iframe nell'interfaccia kitaboo.
3. Stampa come pdf dal browser le varie pagine Parte01.xhtml, Parte02.xhtml, ecc... che ti interessano. Così hai controllo su layout, colori, margini, dimensioni, ecc... L'unico problema di questo approccio è che i link alle figure non funzionano.
Nota bene: è necessario visitare questa pagina dallo stesso browser con cui hai visitato il link originario kitaboo. I cookie che ti imposta non so quanto durino in termini di validità, potrebbo venire rifiutati con un 403 dal server dopo mesi come dopo ore, non ho avuto tempo di testarlo.

Se hai ulteriori dubbi chiedimi.

**Comment by dani9099** [comment]
Ok capito, grazie per il consiglio..farò cosi allora

Immaginavo non fosse una cosa semplice
Comunque con il tuo tool ho scaricato un libro che mi sarebbe scaduto da
qui a breve quindi grazie mille davvero, mi è stato molto utile!




Il giorno mar 22 nov 2022 alle ore 21:57 Francesco Ognibene <
***@***.***> ha scritto:
