### ISSUE TITLE
bSmart

### ISSUE THREAD

**Issue by LentDuck9** [FelixFrog/pdfgrabber#111]
Ho provato a scaricare il pdf di un libro bSmart ma una volta aperto ho notato diverse pagine bianche, senza scritte o corrotte.. 
Grazie in anticipo

**Comment by FelixFrog** [comment]
Prova a cambiare `Compress = no` nel tuo config.ini e a riscaricare i libri in questione. Dovrebbe essere un bug di mupdf

**Comment by LentDuck9** [comment]
ha funzionato, grazie mille
