### ISSUE TITLE
KeyError: b'start' su bSmart

### ISSUE THREAD

**Issue by StarNumber12046** [FelixFrog/pdfgrabber#12]
Nel download di libri bSmart ottengo questo error
Traceback (most recent call last):
  File "C:\Users\franc\reBooks\pdfgrabber\main.py", line 235, in <module>
    main()
  File "C:\Users\franc\reBooks\pdfgrabber\main.py", line 217, in main
    downloadbook()
  File "C:\Users\franc\reBooks\pdfgrabber\main.py", line 144, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\reBooks\pdfgrabber\utils.py", line 41, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\reBooks\pdfgrabber\services\bsm.py", line 103, in downloadbook
    output, md5 = decryptfile(file)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\reBooks\pdfgrabber\services\bsm.py", line 51, in decryptfile
    dec = obj.decrypt(file.read(header[b"start"] - 256 - 16))
                                ~~~~~~^^^^^^^^^^
KeyError: b'start'
durante il "Decrypting pages"

**Comment by FelixFrog** [comment]
Ciao! Grazie di aver segnalato il problema. Questo problema ti capita con tutti i libri o solamente uno in particolare? In ogni caso prova a dare ```python -m pip install --upgrade -r requirements.txt``` per aggiornare i pacchetti richiesti. Ci sono stati dei cambiamenti in ```umsgpack``` recentemente che potrebbe essere la causa del problema.

**Comment by StarNumber12046** [comment]
mi capita con tutti

**Comment by FelixFrog** [comment]
Avrei bisogno di controllare con mano allora, perché non riesco a riprodurre il problem. Riesci a contattarmi a @fflxx su telegram?

**Comment by StarNumber12046** [comment]
a volte funziona ora

**Comment by masteoo** [comment]
@FelixFrog ciao scusa il disturbo, ti ho scritto su tlgram se sai per caso come scaricare i pdf da my.hoepliacademy.it. Grazie ciao

**Comment by Gabboxl** [comment]
Ciao, anche a me si sta verificando lo stesso problema durante il "Decrypting pages". Ho provato più volte con più libri diversi ma restituisce sempre lo stesso errore.
