### ISSUE TITLE
Start problem

### ISSUE THREAD

**Issue by edobett** [FelixFrog/pdfgrabber#13]
When i run "python3 main.py", there are this error:

 File "C:\Users\User\Downloads\pdfgrabber-master\main.py", line 213
    match action:
          ^
SyntaxError: invalid syntax
PS C:\Users\User\Downloads\pdfgrabber-master>

Someone can help me?
Thanks :)

**Comment by Bbalduzz** [comment]
match - case was introduced by python 3.10
I suggest to update your python version ;)
