### ISSUE TITLE
Download tramite Pearson non funzionante - Login a Reader+ restituisce 401 

### ISSUE THREAD

**Issue by MattiaEffendi** [FelixFrog/pdfgrabber#16]
Ciao! Intanto ti ringrazio per aver portato avanti questo progetto che sono sicuro mi sarà molto utile e comodo.

Stavo provando ad utilizzare la funzione di download tramite Pearson: l'account è attivato, un libro collegato e se provo a visitare dal visualizzatore web di Reader+ il libro funziona tutto correttamente. Ho anche installato l'app mobile di Reader+ per vedere se fosse colpa dei termini e condizioni ma purtroppo nulla.

Il problema è il seguente: durante la chiamata a `getrplustoken(username, firstname, lastname)`, Reader+ restituisce un 401 con il seguente messaggio: `User not found in the pulse database`.

L'utente, però, esiste: la chiamata alle API di etext infatti funzionano correttamente restituendo le informazioni su di me.

Questo chiaramente non mi permette di loggare in Pearson perchè il token non è valorizzato nella risposta alla chiamata che ho descritto sopra.

Ho provato a loggare sia con l'username che con l'indirizzo e-mail.

Sto sbagliando qualcosa? O c'è qualcosa che in generale posso fare per aiutare a debuggare?

Grazie mille ancora per il progetto!

**Comment by FelixFrog** [comment]
Ciao! Grazie della segnalazione. Purtroppo non ti so dire il motivo di questo errore, nè so prontamente come risolverlo. Purtroppo sarà una delle mille incongruenze che pearson ha nelle sue stesse API, non ho la più pallida idea di cosa sia il "pulse database". Per ora mi servirebbe che nel file ```servces/prn.py``` aggiungessi dopo la linea 176 un ```print(etextuserinfo)``` e controllassi che, durante il login, la stringa che viene printata contenga sotto la chiave ```username``` lo stesso username che utilizzi per fare il login. Nel caso in cui i due username non coincidano, sistemare il problema è molto semplice. 
Hai per caso aperto il tuo account molto tempo fa/molto recentemente? Fammi sapere!

**Comment by MattiaEffendi** [comment]
Ho provato a printare il dato che mi hai chiesto ed effettivamente gli username combaciano.

L'account in realtà è stato aperto un po'di tempo fa (mi sembra un paio d'anni), però ho loggato solo oggi per la prima volta in Reader+. L'unica cosa che mi viene in mente è che probabilmente Pearson abbia un cron o qualcosa (eseguito probabilmente una volta al giorno, di notte magari) che importa gli utenti in questo fantomatico "pulse database".

A questo punto ti direi che aspetto magari domani o comunque qualche giorno e vediamo se cambia qualcosa!

Intanto grazie per la risposta, tutti gli altri provider funzionano benissimo ed il tool è super comodo.

Buona serata!

**Comment by FelixFrog** [comment]
Il libro che hai è reader+ o etext? Perché se è un libro reader+ e riesci a leggerlo dall'app ufficiale allora è un problema anche di pdfgrabber oltre che della pearson (che di problemi ne ha già tanti)

**Comment by MattiaEffendi** [comment]
Il libro è Reader+, ho paura che comunque sia dovuto al fatto che Pearson ha fatto dei cambiamenti strani alle sue API recentemente (guardando anche altre repo di downloader Pearson tante sono state archiviate perchè appunto negli ultimi 20/25 giorni Pearson ha introdotto di captcha o robe simili nelle API).

Ho paura sia colpa di questo, ed in questo caso probabilmente l'unico modo è recuperare il token di autenticazione dal localstorage tramite un browser autenticato e passarlo in pdfgrabber, prendi tutto con le pinze però perchè non ho assolutamente idee precise a riguardo.

Se ti serve altro sono qui!

**Comment by FelixFrog** [comment]
Ok allora mi sa che comunque in questi giorni ci darò un'occhiata approfondita. Il vantaggio di fare il reverse engineering dell'app mobile è che non possono permettersi di cambiare API ogni due per tre perché per loro è costoso e risulta un disservizio parziale per gli utenti dover aggiornare l'app ogni mesetto. Comunque a me funziona ancora per tutti i vari account che ho.

**Comment by MattiaEffendi** [comment]
Lato mio ti farò sapere se la situazione si risolve da sola o comunque se ti serviranno più informazioni chiedi pure e ti mando ciò che ho.

Felice di sapere che funzioni ancora per gli altri account, allora potrebbe darsi che il problema sia solo mio o che comunque sia una questione di tempo.

Ti ringrazio!

**Comment by Idontgivefuck** [comment]
@MattiaEffendi Probabilmente è un problema tuo, poichè ho appena provato a scaricare un Ebook da Pearson e tutto funziona correttamente! Probabilmente il problema è stato risolto correttamente dall'owner del progetto.

**Comment by FelixFrog** [comment]
Sicuramente collegata a #37. Come per le altre, chiudo questa per spostare la discussione lì.
