### ISSUE TITLE
Add VitalSource support

### ISSUE THREAD

**Issue by bludiprussia** [FelixFrog/pdfgrabber#17]
Ciao, innanzitutto vorrei ringraziarti per aver sviluppato questo programma, mi sta semplificando di molto lo studio :)

Volevo chiederti se ci fosse la possibilità di aggiungere la biblioteca di VitalSource alle opzioni di download.

Se sì, fammi sapere come posso esserti utile in fase di testing, mi farebbe piacere dare una mano!

**Comment by FelixFrog** [comment]
Ciao! Mi fa piacere sapere che il programma ti è utile! Per quanto riguarda VitalSource non ho nessuna esperienza, è una libreria online? In ogni caso mi farebbe piacere darci un'occhiata, unico problema è che non possiedo un account con dei libri. Se ti va puoi contattarmi a @fflxx su telegram
