### ISSUE TITLE
dubbio scuolabook

### ISSUE THREAD

**Issue by artifix100** [FelixFrog/pdfgrabber#19]
ciao se uso lo script per scuolabook mi vale come nuova installazione ? visto che è molto restrittivo nell'uso della app solo due cioè su due dispositivi , con il cambio di due device all'anno, non vorrei giocarmi quelle. grazie

**Comment by FelixFrog** [comment]
Ciao! Sì scuolabook purtroppo per poter scaricare i libri ha bisogno di registrarsi come dispositivo. In ogni caso siccome quel token poi ha durata illimitata non divresti mai più aver bisogno di fare il login. In ogni caso salvatelo!

**Comment by artifix100** [comment]
Grazie informazioni e come si fa a salvare il token?

**Comment by FelixFrog** [comment]
pdfgrabber te lo selva automaticamente, ma per sicurezza se vuoi utilizzarlo magari in un secondo momento o con un'altra installazione di pdfgrabber salvati la stringa verde che printa dopo aver fatto il login "your token is..."
