### ISSUE TITLE
bsmart e booktab errore download

### ISSUE THREAD

**Issue by lui75** [FelixFrog/pdfgrabber#2]
Ho provato a scaricare dei libri da booktab e bsmart (stesso libro della zanichelli), ma il download non parte.
Ecco l'errore:
<img width="570" alt="Schermata 2022-10-18 alle 19 50 24" src="https://user-images.githubusercontent.com/93086027/196506948-a84e59a6-f487-4b0c-b02b-f65cd2833ee8.png">
<img width="570" alt="Schermata 2022-10-18 alle 19 49 57" src="https://user-images.githubusercontent.com/93086027/196506959-5645f2e3-acfd-41d6-ae68-db09aa2c8d2a.png">

**Comment by FelixFrog** [comment]
Ora anche il problema su booktab dovrebbere essere stato sistemato con 5610dacdae7e1bd0af15faa567422505bfd964cc. Grazie della segnalazione!
