### ISSUE TITLE
errore iniziale

### ISSUE THREAD

**Issue by Tabiaso** [FelixFrog/pdfgrabber#20]
Premetto che non sono molto esperto in programmazione, ma quando eseguo "python main.py", mi restituisce il seguente errore:

```
Traceback (most recent call last):
  File "C:\Users\Downloads\pdfgrabber-master\main.py", line 1, in <module>
    import utils
  File "C:\Users\Downloads\pdfgrabber-master\utils.py", line 2, in <module>
    import fitz
ModuleNotFoundError: No module named 'fitz'
```

Ho la versione 3.10 di Python.
Qualcuno può aiutarmi? Grazie in anticipo

**Comment by Bbalduzz** [comment]
hey ciao! Prima di eseguire lo script hai installato tutti i requirements?
Nel caso tu non lo abbia fatto basta che esegui `pip install -r requirements.txt`
