### ISSUE TITLE
Supporto per Raffaello Player

### ISSUE THREAD

**Issue by TorgeTorge** [FelixFrog/pdfgrabber#21]
Ciao,
Mi chiedevo se ci fosse la possibilità di aggiungere il supporto anche per Raffaello, ho dei libri che vorrei salvare in PDF ma non riesco in modo autonomo.
Grazie.

**Comment by FelixFrog** [comment]
Ciao!
Mi fa piacere sentire che c'é qualcuno che vuole scaricare libri da raffaello player. Avevo già in mente di aggiungere la script da molto tempo ma non ho mai trovato nessuno che ne avesse realmente bisogno. Ora ci guardo approfonditamente e ti saprò dire!

**Comment by TorgeTorge** [comment]
> Ciao! Mi fa piacere sentire che c'é qualcuno che vuole scaricare libri da raffaello player. Avevo già in mente di aggiungere la script da molto tempo ma non ho mai trovato nessuno che ne avesse realmente bisogno. Ora ci guardo approfonditamente e ti saprò dire!

Se ti serve qualche dato scrivi pure, io ho un libro acquistato con la versione digitale. Grazie mille per il lavoro che stai facendo!

**Comment by FelixFrog** [comment]
@TorgeTorge con l'ultimo aggiornamento ho aggiunto raffaello player. Dimmi se riscontri problemi con il tuo libro, dato che io avevo accesso ad un account con pochi libri e quindi potrebbe essere ancora molto grezzo

**Comment by TorgeTorge** [comment]
> @TorgeTorge con l'ultimo aggiornamento ho aggiunto raffaello player. Dimmi se riscontri problemi con il tuo libro, dato che io avevo accesso ad un account con pochi libri e quindi potrebbe essere ancora molto grezzo

Funziona alla perfezione, grazie ancora
