### ISSUE TITLE
Problema Pearson Etext

### ISSUE THREAD

**Issue by Merendino1234** [FelixFrog/pdfgrabber#28]
Ciao, per prima cosa ti ringrazio per ciò che fai, io ho un problema con un solo libro della Pearson (Engage 2 PLUS)

Ti lascio lo screen del cmd/powershell
io ho anche la zip che contiene l'epub ma è protetta da password se ti può essere utile te la posso dare
![image](https://user-images.githubusercontent.com/78469030/217622092-4bfb31ad-26c0-4365-9d49-e273925bab67.png)

**Comment by bearillio** [comment]
ciao! anche a me sta dando lo stesso problema e non so come risolvere (il libro è Fisica. Modelli teorici e problem solving. 1)
