### ISSUE TITLE
Oxford Learner's Bookshelf - list index out of range

### ISSUE THREAD

**Issue by lui75** [FelixFrog/pdfgrabber#3]
Ho molti libri oxford e nello scaricare la lista lo script ha restituito l'errore 

Choose a service [bsm/ees/hby/mcm/myl/prn/sbk/znc/dbk/olb]: olb
Do you have a token for Oxford Learner’s Bookshelf? [y/n] (n): n
Oxford Learner’s Bookshelf username: luigi.conversini@gmail.com
Oxford Learner’s Bookshelf password: 
Logged in, your token is 
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImRNclA3VEotbExNMEhOUzNqSkRqTyJ9.eyJ
odHRwczovL2VkdS5vdXAuY29tL1VzZXJJZCI6IjhhZjJiZjBjNTBiODEwMTkwMTUxNDQxZDcyMmQxZWF
kIiwiaHR0cHM6Ly9lZHUub3VwLmNvbS9pc1NvY2lhbCI6ZmFsc2UsImh0dHBzOi8vZWR1Lm91cC5jb20
vdG5jQWNjZXB0ZWQiOnRydWUsImdpdmVuX25hbWUiOiJMdWlnaSIsImZhbWlseV9uYW1lIjoiQ29udmV
yc2luaSIsIm5pY2tuYW1lIjoibHVpZ2kuY29udmVyc2luaSIsIm5hbWUiOiJsdWlnaS5jb252ZXJzaW5
pQGdtYWlsLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3MuZ3JhdmF0YXIuY29tL2F2YXRhci9iMGU4OGV
jNTI2NWE3NjdmMGViNzRiNWUxYjA5NzdlZT9zPTQ4MCZyPXBnJmQ9aHR0cHMlM0ElMkYlMkZjZG4uYXV
0aDAuY29tJTJGYXZhdGFycyUyRmx1LnBuZyIsInVwZGF0ZWRfYXQiOiIyMDIyLTEwLTE4VDE3OjUzOjE
zLjgxNFoiLCJlbWFpbCI6Imx1aWdpLmNvbnZlcnNpbmlAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQ
iOnRydWUsImlzcyI6Imh0dHBzOi8vaWQub3VwLmNvbS8iLCJzdWIiOiJhdXRoMHw4YWYyYmYwYzUwYjg
xMDE5MDE1MTQ0MWQ3MjJkMWVhZCIsImF1ZCI6IkhKNXVrNWFFano1OTBabk5sajQxT3RtQ1EzcHNnT1F
wIiwiaWF0IjoxNjY2MTE1NTk0LCJleHAiOjE2NjYyMDE5OTQsInNpZCI6InhaR0tKMTNjTE9mbWNoSjl
OVTNCSFNyTFNtc09TdzFNIn0.rvF6XsMpEOVxrHJVq1EDZQhGWyyvVq2SIfqDw-PdJwex9fX-6rU823p
JbuMPJalxTTufRIRGHPPMNXHSay7VsH1ef1wUXE8weGC6_tPtoIo0OiadnzRVuqj3bNjaD7wl2dcbcxx
kr_P-EDY-dEjM42uHwl1rXU9H2RrG9MH0gsrknRZDt2qriT8hWFSQYWnyfNeP8w8mVOdoduzzZxA4tNk
fqFxf8bHLUJ5rdOVyk9Axb1mGUUPhuDyPmZHpl9fxBEqTn2pKxECulhfWS9QZmpgDRbhwErmjVig2st1
muV6y3THNoo62a-q0G03R7N5YUqbfq2ih7m6iZ0rvP5rrgQ
Traceback (most recent call last):
  File "/Users/luigi/Documents/pdfgrabber-master/main.py", line 173, in <module>
    main()
  File "/Users/luigi/Documents/pdfgrabber-master/main.py", line 159, in main
    downloadbook()
  File "/Users/luigi/Documents/pdfgrabber-master/main.py", line 99, in downloadbook
    coverpath = utils.cover(service, token, bid, book)
  File "/Users/luigi/Documents/pdfgrabber-master/utils.py", line 52, in cover
    open(coverpath, "wb").write(service.cover(token, bookid, data))
  File "/Users/luigi/Documents/pdfgrabber-master/services/olb.py", line 125, in cover
    book = bookinfo["msg"]["content_list"][0]
IndexError: list index out of range
luigi@George pdfgrabber-master %

**Comment by FelixFrog** [comment]
Il problema è che a quanto pare esistono collezioni di libri su olb di cui non ero a conoscenza, e il codiece non è pronto a gestire queste evenienze. Grazie di avermelo fatto scoprire. Troverò una soluzione per scaricare anche le collezioni complete ;-)

**Comment by lui75** [comment]
Se mi scrivi su Twitter @luemek ti invio le credenziali di Oxford Learner’s Bookshelf. Così puoi testare il tuo script.
