### ISSUE TITLE
Palumbo editore 

### ISSUE THREAD

**Issue by artifix100** [FelixFrog/pdfgrabber#31]
ciao felix , ti avevo contattato anche su Telegram  a proposito di Palumbo editore , poi non ho più avuto notizie :) è successo qualcosa ciao grazie in ogni caso

**Comment by FelixFrog** [comment]
Il support è stato aggiunto in 32da0bc72ff9fb9a27de88fc585f714c08ce4bb1. Chiudo la issue ;-)
