### ISSUE TITLE
Supporto a MyPearsonPlace

### ISSUE THREAD

**Issue by Ale1x** [FelixFrog/pdfgrabber#32]
Salve, volevo sapere se in futuro prossimo verrà aggiunto il supporto al download per MyPearsonPlace dato che esso non ha nemmeno un'app per rendere disponibili i libri Offline è molto scomodo, grazie in anticipo.

**Comment by FelixFrog** [comment]
pdfgrabber ora supporta MySanomaPlace che dovrebbe aver rimpiazzato MyPearsonPlace

**Comment by Ale1x** [comment]
Ciao @FelixFrog non credo che siano le stesse piattaforme.

Per MyPearson place accedo qui: https://it.pearson.com/registrazione-login.html (Cliccando su Higher Education a sx).
