### ISSUE TITLE
Zanichelli link changes

### ISSUE THREAD

**Issue by teo2600** [FelixFrog/pdfgrabber#34]
Mi pare di capire che Zanichelli ha appena modificato la codifica del link, ora è:

https://webmy.zanichelli.it/ebook/XXXXXXXXXXXXX?origPlatform=https://my.zanichelli.it&origSection=bookmarks&_gl=1*1mehjuz*_ga*NjM5NzczNDA1LjE2ODEzNzE3MTI.*_ga_FL8QBN8HHQ*MTY4MTQ5MzU0MS43LjEuMTY4MTQ5Njk3MS4wLjAuMA..

Questa diventa la nuova interfaccia web di lettura:

https://webreader.zanichelli.it/6.0/zanichelli/#/reader?mode=online

E le (immagini delle) pagine mi sembrano queste:

https://.../page0010.svgz

Lo script attualmente salva il file pdf, ma solo la prima pagina risulta visibile...

**Comment by alterwilhelm** [comment]
Sono ulteriormente cambiati un'altra volta i link?
