### ISSUE TITLE
Scuolabook not retrieving book list

### ISSUE THREAD

**Issue by teo2600** [FelixFrog/pdfgrabber#35]
Non viene recuperata la lista dei libri Scuolabook...

**Comment by Bbalduzz** [comment]
Ciao :) Controlla il numero di dispositivi collegati al tuo account.
Puoi vederli qua: [https://www.scuolabook.it/customerdevices/device](https://www.scuolabook.it/customerdevices/device).
Ti consiglio di eliminare se presente GOOGLE-PIXEL_5 (indica pdfgrabber) e di riautenticarti su pdfgrabber ;)
