### ISSUE TITLE
se ebook multimediale, crea un pdf funzionante, ma non riempie l'intera pagina

### ISSUE THREAD

**Issue by alterwilhelm** [FelixFrog/pdfgrabber#36]
Salve, questo script è uno spettacolo , ancora davvero grazie!

Una cosa da niente, una piccolezza, ma che non rende la lettura da tablet proprio comoda: quando scarico da znc un libro taggato come ebook multimediale, il pdf risulta funzionante e completo, ma ogni pagina è ridimensionata per riempire solo circa 3/4 in alto a sx della pagina intera. è possibile ridimensionarli a tutta pagina?

Grazie in anticipo, e ancora davvero grazie

**Comment by dstasio** [comment]
Ciao, se ancora non hai trovato una soluzione, puoi provare [Briss](https://github.com/mbaeuerle/Briss-2.0).
Ha un'interfaccia un po' scomoda ma per me ha funzionato perfettamente.

**Comment by Bbalduzz** [comment]
E' un problema che ne' io ne' FelixFrog (molto più bravo di me) siamo riusciti ne' a spiegarci ne' a risolvere.
la linea [293](https://github.com/FelixFrog/pdfgrabber/blob/02b9b79c48b6ecfd1fb3d6e86044fef775bc854d/services/znc.py#L293C6-L293C6) si occupa di trovare sia l'altezza che la larghezza delle pagine:
`sizematch = re.search('content.+?width\s{,1}=\s{,1}([0-9]+).+?height\s{,1}=\s{,1}([0-9]+)', open(fullpath, encoding="utf-8").read())`
La cosa strana e' che anche se le dimensioni della pagina sono corrette, viene renderizzata male.

**Comment by FelixFrog** [comment]
Ora dovrebbe essere tutto sistemato. Chromium ha cambaito i dpi di default da 96 a 144, e playwright non ha aggiornato.
La soluzione non è ancora perfetta perché lascia un bordo bianco di qualche pixel in basso e a destra. Bisognerà attendere che le build di chromium che usa playwright incorporino questo fix https://bugs.chromium.org/p/chromium/issues/detail?id=498892
