### ISSUE TITLE
Pearson token error

### ISSUE THREAD

**Issue by teo2600** [FelixFrog/pdfgrabber#37]
Traceback (most recent call last):
  File "/home/xxxxxx/Scaricati/pdfgrabber-master/main.py", line 235, in <module>
    main()
  File "/home/xxxxxx/Scaricati/pdfgrabber-master/main.py", line 217, in main
    downloadbook()
  File "/home/xxxxxx/Scaricati/pdfgrabber-master/main.py", line 86, in downloadbook
    token = utils.login(service, username, password)
  File "/home/xxxxxx/Scaricati/pdfgrabber-master/utils.py", line 30, in login
    token = service.login(username, password)
  File "/home/xxxxxx/Scaricati/pdfgrabber-master/services/prs.py", line 187, in login
    rplususerinfo = getrplususerinfo(rplustoken["token"])
KeyError: 'token'

**Comment by gabrySerra** [comment]
I have the same problem.
Have you solved?

" Error: Unable to authenticate to Pearson eText / Reader+ "

**Comment by teo2600** [comment]
> I have the same problem. Have you solved?
> 
> " Error: Unable to authenticate to Pearson eText / Reader+ "

No

**Comment by Bbalduzz** [comment]
That's likely a problem with the pearson api, not FelixFrog script.
If u do a requests check when logging in the phone application, the response to the login request is the same, even tho you can access the app.
I'll attach the demonstration:

request | response
:-: | :-:
![request](https://github.com/FelixFrog/pdfgrabber/assets/81587335/999295e3-3d55-44d8-a7b0-48201fdd91e2) | ![response](https://github.com/FelixFrog/pdfgrabber/assets/81587335/93accebe-85b6-41cc-981d-bb4761efe192)

**Comment by FelixFrog** [comment]
This could mean two things:
 - the login system has more quirks and escrow systems than previously thought
 - there are some accounts that do not have rplus credentials (and maybe rplus ones without etext ones)
In either case some work is required, especially in the second case. If the latter turns out to be true, we could think about splitting prs in two, since it is already too complex to maintain in one piece.
If it is an easy fix (or if I figure out a quick workaround) I'll push it out as soon as possible. In any case it should be sorted out by mid september.

**Comment by FelixFrog** [comment]
Questa issue teniamo la discussione principale. Il problema dovrebbe essere sttao risolto. Qualcuno che aveva sofferto di questo errore mi faccia sapere.

**Comment by GiacomoStark** [comment]
Ciao, il problema è stato risolto, riesco ad ottenere il token (un codice alfanumerico lunghissimo) ma quando lo copio e incollo mi dice questo:
 non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
Inoltre vorrei poi capire come continuare, cioè dovrei inserire l'ISBN del libro e il numero di pagine. Ma come?
Cioè ad esempio ho questo libro: ISBN-13: 9780137348657, come lo digito nel programma e quale numero di pagine devo scrivere se non lo conosco (non c'è scritto da nessuna parte), posso abbondare?

**Comment by FelixFrog** [comment]
@GiacomoStark penso che tu non abbia ben compreso lo scopo di pdfgrabber: questo programma serve per fare "backup" offline di libri che sono fruibili su piattaforme online, come bsmart, pearson myplace, scuolabook, ecc... Quello che vai a fare è fare il login sui loro servizi, selezionare un libro e scaricarlo in formato pdf. Se sei riuscito a fare il login e ti ha restituito un token (che all'utente in realtà non serve a nulla), successivamente ti dovrebbe aver mostrato una lista di libri da cui scegliere. Segui le istruzioni dell'interfaccia ;-)
