### ISSUE TITLE
problemi nell'avvio dell'app

### ISSUE THREAD

**Issue by SHINICI001** [FelixFrog/pdfgrabber#42]
Buongiorno , scusami se ti disturbo, ma non riesco ad avviare l'applicazione tramite python (e di conseguenza non riesco a scaricare i pdf). Non sono molto pratica con python, ma anche seguendo i passaggi che ci sono mi si blocca tutto.

**Comment by Bbalduzz** [comment]
Ciao, potresti specificare gli eventuali errori che si verificano?

**Comment by SHINICI001** [comment]
PS D:\doc scuola pdf\pdfgrabber-master> python main.py
D:\PYTHON\python.exe: can't open file 'D:\\doc scuola pdf\\pdfgrabber-master\\main.py': [Errno 2] No such file or directory
PS D:\doc scuola pdf\pdfgrabber-master> 
![Immagine 2023-08-26 100322](https://github.com/FelixFrog/pdfgrabber/assets/143200081/3c7105c6-7683-441f-b994-e89c0a4719ef)


(non riesco a far eseguire il programma 😅)

**Comment by Bbalduzz** [comment]
Il problema probabilmente è il nome della cartella di lavoro: `doc scuola pdf`. Ti consiglio di cambiarlo in qualcosa come `doc-scuola-pdf` oppure cambiare nome in qualcosa che non comprenda spazi.
Dimmi se il problema si risolve :)

**Comment by SHINICI001** [comment]
Mi sa che non è un problema relativo al nome della cartella 🤣😂
![Immagine 2023-08-26 143931](https://github.com/FelixFrog/pdfgrabber/assets/143200081/bd9732ca-dfde-41f2-8dc6-ef34ff8a743f)
![Immagine 2023-08-26 143948](https://github.com/FelixFrog/pdfgrabber/assets/143200081/334566a5-f2e9-4074-988a-d937339ab356)

**Comment by Bbalduzz** [comment]
ah, ho visto solo ora.
Non sei nella directory giusta. Se controlli, noti che hai una cartella `pdfgrabber-master` che continere un'ulteriore cartella `pdfgrabber-master`.
Puoi risolvere in due maniere:
1) `cd pdfgrabber-master` e poi `python main.py`
2) sposti la cartella con gli scripts fuori da `pdfgrabber-master`

**Comment by FelixFrog** [comment]
@Bbalduzz ha creato un ottimo tutorial nella issue #14 

Ti consiglio caldamente di seguire quello. Per ora segno questa come completa ;-)
