### ISSUE TITLE
Problema installazione

### ISSUE THREAD

**Issue by GiacomoStark** [FelixFrog/pdfgrabber#43]
Buongiorno @FelixFrog @Bbalduzz , sono un neofita di Python e non so veramente come installare pdfgrabber in Python. Vorrei che qualcuno mi spiegasse come fare perché ho bisogno di consultare un libro di Pearson. Tra l'altro poi vorrei capire come fare per scaricarlo. Grazie mille della disponibilità.

**Comment by Bbalduzz** [comment]
### How to use pdfgrabber
1. download the latest version of [Python](https://www.python.org/downloads/])
    - when installing though the set up wizard, make sure to select the checkbox to add python to `PATH`
    ![img](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Flinuxhint.com%2Fwp-content%2Fuploads%2F2022%2F09%2FHow-to-Add-Python-to-Windows-Path-3.png&f=1&nofb=1&ipt=6324f391e317600b0eaa0586b2846e63bcb997e909d93f61ea46fdeb32019fd5&ipo=images)
2. downlaod the pdfgrabber repo
    - using git: `git clone https://github.com/FelixFrog/pdfgrabber.git`
    - manually: download the zip (green button labeled "code") and extract it
3. open your local clone of pdfgrabber
4. open the terminal in that directory and run:
    1) `pip install -r requirements.txt` (takes care of installing every needed libraries)
    2) run the script
        - `python3 main.py` (linux and macos) 
        - `py main.py` (windows)
5. once inside the pdfgrabber CLI:
    - press `r`: register a new account
    - choose what to do (it's listed):
       - to download a book: press `d` and follow the instructions

From here the pdfgrabber cli guides you well

**Comment by GiacomoStark** [comment]
Grazie, sono riuscito ad andare avanti, ma non riconosce le credenziali dell'account Pearson che inserisco.

**Comment by FelixFrog** [comment]
Ciao! Prima di tutto ringrazio @Bbalduzz del tutorial, che spero aggiunga prontamente con un commit al readme.

In secondo luogo il bug di pearson é già conosciuto e si sta lavorando per risolverlo. Ad ora potresti provare a scaricare l'app pearson readerplus sul tuo dispositivo mobile, fare il login lì almeno una volta e riprovare a fare il login su pdfgrabber. In ogni caso facci sapere su questa issue se funziona o no.

**Comment by GiacomoStark** [comment]
Ciao, allora sono riuscito ad entrare nell'app Pearson Plus, sito dove mi sono iscritto, ed anche nell'app Reader+. (L'username è la mail) In realtà sono riuscito ad andare avanti ma mi dà comunque errore, che allego:

Choose a service [bsm/ees/hbs/mcm/myl/prs/sbk/znc/dbk/olb/rfl]: prs
Do you have a token for Pearson eText / Reader+? [y/n] (n): n
Pearson eText / Reader+ username: ***********
Pearson eText / Reader+ password: ***********
Traceback (most recent call last):
  File "C:\Users\ronal\Downloads\pdfgrabber-master\main.py", line 235, in <module>
    main()
  File "C:\Users\ronal\Downloads\pdfgrabber-master\main.py", line 217, in main
    downloadbook()
  File "C:\Users\ronal\Downloads\pdfgrabber-master\main.py", line 86, in downloadbook
    token = utils.login(service, username, password)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronal\Downloads\pdfgrabber-master\utils.py", line 30, in login
    token = service.login(username, password)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronal\Downloads\pdfgrabber-master\services\prs.py", line 187, in login
    rplususerinfo = getrplususerinfo(rplustoken["token"])
                                     ~~~~~~~~~~^^^^^^^^^
KeyError: 'token'

Vorrei capire cosa è il token.

**Comment by FelixFrog** [comment]
Duplicato della issue #37, segno questa come completa. Segui lì la discussione.
