### ISSUE TITLE
FileNotFoundError when reaching 1/3 of the book on Zanichelli Reader

### ISSUE THREAD

**Issue by RiccardoWilliam** [FelixFrog/pdfgrabber#46]
I don't know why it stops at exactly the 175th page of the book everytime i try to download it, no errors while downloading other books but this one that i recently added to my library give the same error everytime, here's python traceback:

Traceback (most recent call last):
  File "C:\Users\riccw\Desktop\pdfgrabber-master\main.py", line 245, in <module>
    main()
  File "C:\Users\riccw\Desktop\pdfgrabber-master\main.py", line 227, in main
    downloadbook()
  File "C:\Users\riccw\Desktop\pdfgrabber-master\main.py", line 153, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\riccw\Desktop\pdfgrabber-master\utils.py", line 41, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\riccw\Desktop\pdfgrabber-master\services\znc.py", line 366, in downloadbook
    pdf, toc, labels = downloadkitaboo(token, bookid, pdf, toc, labels, progress, skipfirst)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\riccw\Desktop\pdfgrabber-master\services\znc.py", line 296, in downloadkitaboo
    sizematch = re.search('content.+?width\s?=\s?([0-9]+).+?height\s?=\s?([0-9]+)', open(fullpath, encoding="utf-8").read())
                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\riccw\\AppData\\Local\\Temp\\kitaboo.5oxgllyy\\OPS\\page0175.xhtml'

**Comment by FelixFrog** [comment]
[Contact me](https://tg.me/fflxx) please

**Comment by FelixFrog** [comment]
As of now the error seems to be on zanichelli's side. I guess the only option is to wait. A workaround that adds a blank page in place of the missing one has been added in 79498f5b61ff57247a1878b9b5d0420809227f66 which should close the issue.
