### ISSUE TITLE
Errors in ZNC

### ISSUE THREAD

**Issue by taddeus73** [FelixFrog/pdfgrabber#48]
There wan an error when downloading from znc for some books
<img width="1732" alt="Screenshot 2023-09-17 at 08 51 09" src="https://github.com/FelixFrog/pdfgrabber/assets/2022611/5fe15263-65c1-4cca-97ed-12d107a58081">

**Comment by Bbalduzz** [comment]
Ciao! E' un problema con playwright.
Hai eseguito `playwright install` una volta dopo aver installato la libreria con `pip`?

**Comment by taddeus73** [comment]
no... I', going to try this ...

**Comment by taddeus73** [comment]
It works! thanks
