### ISSUE TITLE
Downloader for tutorialspoint

### ISSUE THREAD

**Issue by taddeus73** [FelixFrog/pdfgrabber#49]
Is there a pdfgrabber for tutorialspoint ? I need to download some bought books  from my personal area

**Comment by Bbalduzz** [comment]
neither me or felixfrog have access to tutorialspoint's books. 
I checked out their reader with a free book and it seems that they provide you with the full pdf object in the request to:
`https://www.tutorialspoint.com/market/ebook/{book_name}/load.jsp`.

For now, if u want to download your books copy that requests as cURL, paste it in [here](https://curlconverter.com/), copy the python script and add this:

```
with open(f"{response.url.split('/')[5]}.pdf", "wb") as f:
    f.write(response.content)
```
to the end of the python file

I'll attach a demo:

https://github.com/FelixFrog/pdfgrabber/assets/81587335/dc5f3781-7ea6-400d-afef-2baa3e0e3082

**Comment by taddeus73** [comment]
Great! it works fine!
thanks
