### ISSUE TITLE
Download kitaboo senza autenticazione

### ISSUE THREAD

**Issue by cwke** [FelixFrog/pdfgrabber#5]
i libri kitaboo possono essere visualizzati senza aver eseguito l'accesso all'account myzanichelli.
es. https://my.zanichelli.it/kitaboo/635d1f2b65cf21254fce75ab6454740a  
Questo link si puo ottenere dalla liberira -> "leggi libro online" -> copia link

Vorrei scaricare un paio di libri, però ho a disposizione solamente questi link

**Comment by FelixFrog** [comment]
Ciao! Grazie della segnalazione, non ero al corrente di questa funzionalità, e come sempre l'incompetenza di questi servizi non si smentisce. Per ora pdfgrabber non é in grado di fare dei download da script "one-shot" (ossia senza login). Ci ho comunque dato un'occhiata, magari in un futuro potrei aggiungere questo tipo di script (avrei già anche in coda uno script di questo genere per giuntitvp) e cercare di venirne a capo di tutto qul caching che il webreader kitaboo fa.

In ogni caso penso che la miglior soluzione per te in questo momento sia fare il login con l'account che possiede quel libro (sempre se ti interessa avere tutte le features aggiuntive di pdfgrabber come il testo selezionabile, indice, pagine selezionabili, etc...)

**Comment by FelixFrog** [comment]
Comunque con 0b4cb3c430b22480d899412be6153cfefcddb06f ho aggiunto la possibilità di scaricare questi link. Fammi sapere se hai problemi
