### ISSUE TITLE
Scuolabook ends its service

### ISSUE THREAD

**Issue by Bbalduzz** [FelixFrog/pdfgrabber#50]
### Informazione per chi riscontrera' problemi con Scuolabook
![image](https://github.com/FelixFrog/pdfgrabber/assets/81587335/fb0d5aa8-7977-4eb6-880f-9566e92a1edd)

**Transcript:**
> GENTILE UTENTE,
>Scuolabook cessa la sua decennale attività al servizio delle scuole, dei docenti, degli studenti e delle famiglie.
>- Dallo scorso 15 luglio non è più possibile effettuare nuovi acquisti di libri in formato digitale o procedere a nuove iscrizioni a >corsi di formazione
>- Dal prossimo 30 settembre non si potranno più utilizzare codici coupon per scaricare gratuitamente copie di libri cartacei in >formato digitale
>- Fino al 31.12.2023 resta comunque disponibile la consultazione dei testi già presenti sulla tua libreria

>Per rendere la transizione il più agevole possibile, ti indichiamo di seguito, il link su cui potrai reperire, a partire dal 1° ottobre, i testi scolastici delle case editrici che hanno provveduto a comunicarlo:
>- Società Editrice Internazionale S.p.A: [www.lascuolasei.it](https://www.lascuolasei.it/)
>- La Scuola S.p.A: [www.lascuolasei.it](https://www.lascuolasei.it/)
>- Simone S.r.l: [www.bsmart.it](https://www.bsmart.it/)
>- RAFFAELLO LIBRI S.p.A: [www.store.bsmart.it](https://www.store.bsmart.it/)
>- Dentalstore & Edizioni Lucisano S.r.l.: [www.didattica-odontoiatrica.it](https://www.didattica-odontoiatrica.it/)
>Scrivi a [info@scuolabook.it](mailto:info@scuolabook.it) per avere ulteriori informazioni.
>Grazie per la fiducia dimostrata fino ad oggi

Tutte le sovracitate case editrici adotteranno **bsmart**

**Comment by FelixFrog** [comment]
Mmmhh.... In un certo senso sono quasi dispiaciuto, erano gli unici che almeno ci provavano a mettere qualche tipo di misura di sicurezza 🤣 
Scherzi a parte, dovrebbe essere un grossa vittoria per tutti, dato che bsmart è molto meno restrittivo in termini di login e robe varie. Non chiudo la issue fino a che non specificherò in qualche modo questa cosa all'utilizzo di sbk
