### ISSUE TITLE
Visualizzare più di 10 libri

### ISSUE THREAD

**Issue by beninifez** [FelixFrog/pdfgrabber#51]
ciao, sul mio account booktab avendo tutti i libri che ho usato(quindi anche quelli delle medie), in totale sono più di 10. C'è un modo di visualizzarne più di 10?

**Comment by FelixFrog** [comment]
Ciao! pdfgrabber è in grado di scaricare tutti i tuoi libri. Probabilmente è una questione di scrolling nella tua interfaccia. Se così non fosse ciò significa che booktab ti fa visualizzare delle raccolte che magari fanno sembrare la lista ufficiale più corposa di quella di pdfgrabber.
