### ISSUE TITLE
scusate l'ignoranza...

### ISSUE THREAD

**Issue by darzan** [FelixFrog/pdfgrabber#54]
...ma quando mi trovo di fronte la riga:
`What do you want to do? ((r)egister new user, (d)ownload from your libraries, download from a (o)ne-shot link, (l)ogout, manage (t)okens, (v)iew all books, (q)uit) [r/d/o/l/t/v/q] (d)`
...non capisco cosa/come fare a scaricare un libro che ho su zan1che11i.

**Comment by Bbalduzz** [comment]
quello che vedi nella prima parentesi tonda è la lista di cose che puoi fare. Quindi:
```
- register new user
- download from your libraries
- download from a one-shot link
- logout
- manage tokens
- view all books
-  quit
```
la prima lettera di ogni azione (eccetto per gli one-shot links) rappresenta un comando, che sono quindi rispettivamente:
`[r/d/o/l/t/v/q]`

Per usare pdfgrabber devi "registrare" un account (premi <kbd>r</kbd>). Questo account effettivamente non serve a nulla, quindi puoi anche mettere due <kbd>enter</kbd> e va tutto come dovrebbe, se invece decidi di usare un username e password serie, ricordateli per i futuri ultilizzi

Una volta registrato l'account, per scaricare i libri premi <kbd>d</kbd>, qui ti farà vedere tutti i servizi supportati:
```
          Available services           
┏━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Code ┃ Name                         ┃
┡━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ bsm  │ bSmart                       │
│ ees  │ easyeschool                  │
│ hbs  │ Mondadori HUB Scuola         │
│ mcm  │ MEE2                         │
│ myl  │ MyLim                        │
│ prs  │ Pearson eText / Reader+      │
│ sbk  │ Scuolabook                   │
│ znc  │ Zanichelli Booktab / Kitaboo │
│ dbk  │ Laterza diBooK               │
│ olb  │ Oxford Learner’s Bookshelf   │
│ rfl  │ Raffaello Player             │
│ cmb  │ Cambridge GO                 │
└──────┴──────────────────────────────┘
Choose a service [bsm/ees/hbs/mcm/myl/prs/sbk/znc/dbk/olb/rfl/cmb]: 
```
qui dovrai scegliere il servizio da cui scaricare il tuo libro, digitando rispettivamente uno di questi comandi:
`[bsm/ees/hbs/mcm/myl/prs/sbk/znc/dbk/olb/rfl/cmb]`

successivamente dovrai accedere al tuo account del servizio scelto, ti chiederà quale libro/i della tua libreria vuoi scaricare e avrai fatto.

**Comment by FelixFrog** [comment]
Thx @Bbalduzz, I'll close the issue
