### ISSUE TITLE
Use with appBook

### ISSUE THREAD

**Issue by SimoneMSR** [FelixFrog/pdfgrabber#55]
Hello,

I would like to use this tool with appbook. 

Could you show me a way to manage? I have a book code if this can be useful

I see that each time I click on "next page" a request like this is sent

`filesystem:https://appbook.elionline.com/persistent/385/book_1303/pages/1470224163019.png`

**Comment by Bbalduzz** [comment]
As far as I know, neither me and FelixFrog have access to appbook's ebooks. 
You can contact privately FelixFrog: https://t.me/fflxx
or me: https://t.me/edobal

**Comment by Bbalduzz** [comment]
Ciao di nuovo, scusa se provvedo solo ora.
Ho scritto un piccolo script che trovi qui [https://github.com/Bbalduzz/appbook-PDF-downloader](https://github.com/Bbalduzz/appbook-PDF-downloader).

Quando avrò tempo lo integrerò a pdfgrabber

**Comment by SimoneMSR** [comment]
Grazie per questo! Mi sembra molto utile
