### ISSUE TITLE
it doesn't see one particular book on myzanichelli

### ISSUE THREAD

**Issue by Lordam1927** [FelixFrog/pdfgrabber#56]
I'm sorry
unfortunately I have a problem with a specific new book that cannot be seen by the script (my others books don't have problems) I'm not sure why, perhaps it could be due to the fact that the latter can only be opened with online reader (laZreader) and not with booktab (probably because zanichelli blocked this)... could you help me?
thanks Loris

**Comment by FelixFrog** [comment]
If the book is not visible on the official booktab app, there's no way for pdfgrabber to download it, since it is communicates with the booktab api. This has to be fixed on their end.
