### ISSUE TITLE
`KeyError: 'librodigital_json_abs_1_idclase_385592325_idcurso_4036182_type_json_xdevice_ipadapp.htm'`

### ISSUE THREAD

**Issue by alexanderadam** [FelixFrog/pdfgrabber#58]
Hello @FelixFrog,

thank you so much for pdfgrabber. Unfortunately I'm running into the following issue when trying to download from Blinklearning:

```
Select a book or a comma-separated list of books: 0
Appending units ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━  92% 0:00:03
Traceback (most recent call last):
  File "/home/user/pdfgrabber/main.py", line 260, in <module>
    main()
  File "/home/user/pdfgrabber/main.py", line 242, in main
    downloadbook()
  File "/home/user/pdfgrabber/main.py", line 163, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/pdfgrabber/utils.py", line 41, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/pdfgrabber/services/blk.py", line 20, in downloadbook
    return mcm.downloadbook(token, bookid, data, prorgess, blinklearning_baseurl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/pdfgrabber/services/mcm.py", line 116, in downloadbook
    sujson = json.loads(files["librodigital_json_abs_1_idclase_" + subunit["id"] + "_idcurso_" + bookid + "_type_json_xdevice_ipadapp.htm"])
                        ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'librodigital_json_abs_1_idclase_385592325_idcurso_4036182_type_json_xdevice_ipadapp.htm'
```

Any idea how to fix this?

**PS:** there also seem to be a little typo at `prorgess`

**Comment by LesGaR** [comment]
> Hello @FelixFrog,
> 
> thank you so much for pdfgrabber. Unfortunately I'm running into the following issue when trying to download from Blinklearning:
> 
> ```
> Select a book or a comma-separated list of books: 0
> Appending units ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━  92% 0:00:03
> Traceback (most recent call last):
>   File "/home/user/pdfgrabber/main.py", line 260, in <module>
>     main()
>   File "/home/user/pdfgrabber/main.py", line 242, in main
>     downloadbook()
>   File "/home/user/pdfgrabber/main.py", line 163, in downloadbook
>     pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/pdfgrabber/utils.py", line 41, in downloadbook
>     pdf = service.downloadbook(token, bookid, data, progress)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/pdfgrabber/services/blk.py", line 20, in downloadbook
>     return mcm.downloadbook(token, bookid, data, prorgess, blinklearning_baseurl)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/pdfgrabber/services/mcm.py", line 116, in downloadbook
>     sujson = json.loads(files["librodigital_json_abs_1_idclase_" + subunit["id"] + "_idcurso_" + bookid + "_type_json_xdevice_ipadapp.htm"])
>                         ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> KeyError: 'librodigital_json_abs_1_idclase_385592325_idcurso_4036182_type_json_xdevice_ipadapp.htm'
> ```
> 
> Any idea how to fix this?
> 
> **PS:** there also seem to be a little typo at `prorgess`

Same error for me

**Comment by masteoo** [comment]
@FelixFrog ciao, scusa il disturbo, purtroppo non riesco a eseguire script su Termux. Se ti passo credenziali di blinklearning.com riusciresti a scaricarmi pdf di 2 libri? Grazie
![Screenshot_20231120_090006_Telegram](https://github.com/FelixFrog/pdfgrabber/assets/120033556/0bd3fbe8-1cef-4fa2-8b44-73d094b0b09b)

**Comment by jgautierit** [comment]
Same issue as @alexanderadam

**Comment by FelixFrog** [comment]
I will close the issue because this should fix the problem. If you still encounter the problem don't hesitate to tell me.

**Comment by alexanderadam** [comment]
@FelixFrog I can confirm that the fix worked perfectly. Thank you!

**Comment by masteoo** [comment]
@FelixFrog ciao, scusami, non ho più sentito nulla circa le anteprime di gobi3.com . 
Grazie
Ciao
