### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by davimeglioli** [FelixFrog/pdfgrabber#6]
Premetto che non sono molto esperto. Una volta eseguito main.py si apre una pagina tutta nera di cmd che si chiude subito dopo. Successivamente si crea una cartella (dentro la cartella pdf grabber) chiamata __pycache__, con all'interno un file chiamato utils.cpython-311.pyc. Come posso risolvere il fatto che non esegue main.py? Ringrazio in anticipo

**Comment by FelixFrog** [comment]
Ciao! Probabilmente python crasha perché non trova le librerie necessarie (o magari qualche altro errore ma a meno che tu non usi una versione vecchia di python non è il caso). Quello che ti consiglio di fare è aprire una finestra del cmd, fare ```cd C:\Users\<tuo nome utente>/<percorso di dove hai scaricato pdfgrabber>```  e poi eseguire ```pip install -r requirements.txt```. Poi a quel punto pui fare ```python main.py``` Se lo esegui facendo doppio click non ti mostra l'errore prima di chiudere la finestra.
