### ISSUE TITLE
File "/Users/errico/Downloads/pdfgrabber-master/./main.py", line 238     match action:           ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by uraverageappdev** [FelixFrog/pdfgrabber#60]
File "/Users/errico/Downloads/pdfgrabber-master/./main.py", line 238
    match action:
          ^
SyntaxError: invalid syntax

**Comment by FelixFrog** [comment]
You need at least python3.10 to use pdfgrabber. Since you are using macOS I advise upgrading it with `brew upgrade python3`.
