### ISSUE TITLE
Pearson Plus gives No books!

### ISSUE THREAD

**Issue by mustafa-ad** [FelixFrog/pdfgrabber#63]
Hello, I want to download a book that I have purchased from Pearson Plus, but it always returns "No books!"

**Comment by FelixFrog** [comment]
Should be fixed by now. Lmk.

**Comment by mustafa-ad** [comment]
It had downloaded part of the book only, 67 pages, the book should have more than 800 pages

**Comment by FelixFrog** [comment]
As of now it should download all the pages.
