### ISSUE TITLE
KeyError: 'encrypted_password'

### ISSUE THREAD

**Issue by valez72** [FelixFrog/pdfgrabber#67]
During fetching library step on pearson+ there is error KeyError: 'encrypted_password' and program quits

During fetching library step on Zanichelli there is error TypeError: 'bool' object is not subscriptable and program quits

**Comment by FelixFrog** [comment]
Does the latest commit 9ed4f24 fix the Zanichelli issue?

**Comment by mustafa-ad** [comment]
> Does the latest commit [9ed4f24](https://github.com/FelixFrog/pdfgrabber/commit/9ed4f24ede344538f67257cdbaa9519b01e4fcf7) fix the Zanichelli issue?

I just tried it, it gives the same error with the latest commit:

`Traceback (most recent call last):
  File "/home/user/Downloads/Compressed/pdfgrabber-master/main.py", line 271, in <module>
    main()
  File "/home/user/Downloads/Compressed/pdfgrabber-master/main.py", line 253, in main
    downloadbook()
  File "/home/user/Downloads/Compressed/pdfgrabber-master/main.py", line 119, in downloadbook
    books = utils.library(service, token)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Downloads/Compressed/pdfgrabber-master/utils.py", line 99, in library
    return service.library(token)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Downloads/Compressed/pdfgrabber-master/services/prs.py", line 220, in library
    books[str(i["book_id"])] = {"title": i["book_title"], "cover": i["cover_image_url"], "isbn": i["isbn"], "type": i["product_model"], "prodid": i["product_id"], "author": i["author"], "pwd": i["encrypted_password"], "url": i["downloadUrl"]}
                                                                                                                                                                                                 ~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'encrypted_password'`
