### ISSUE TITLE
Unsupported format

### ISSUE THREAD

**Issue by mayo90p** [FelixFrog/pdfgrabber#68]
When I go to download my textbooks from pearson+ that begin with the ID BRNT I get this alert:
Unsupported format ETEXT_EPUB_BRONTE!
Any help would be appreciated! Disclaimer: I am very new to python so I could be doing something wrong.

**Comment by FelixFrog** [comment]
Contact me privately on [telegram](t.me/fflxx) so I can take a look and add support for it!
