### ISSUE TITLE
Bsmart Issue

### ISSUE THREAD

**Issue by aleeessio** [FelixFrog/pdfgrabber#7]
Traceback (most recent call last):
  File "/home/panda/pdfgrabber/main.py", line 194, in <module>
    main()
  File "/home/panda/pdfgrabber/main.py", line 178, in main
    downloadbook()
  File "/home/panda/pdfgrabber/main.py", line 134, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
  File "/home/panda/pdfgrabber/utils.py", line 34, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
  File "/home/panda/pdfgrabber/services/bsm.py", line 80, in downloadbook
    if i["resource_type_id"] != 14:
TypeError: string indices must be integers

Penso che sia per via del fatto che l'anteprima è scaduta..per caso c'è un modo per aggirare questo blocco? Grazie in anticipo!
Ne approfitto anche per elogiare il creatore questo mini-programmino a dir poco fantastico, per easyeschool non c'era quasi nulla :)

**Comment by FelixFrog** [comment]
Ciao? Grazie di aver segnalato il problema. Se stavi provando a scaricare una preactivation (ossia anteprima, cioé che non é un libro propriamente tuo) ed é scaduta, allora il problema é sicuramente quello. A meno che non ci sia un modo per visualizzarla anche sul sito bsmart una volta scaduta, allora la risoluzione del bug sarà semplicemnte non mostrare libri scaduti, e quindi non permettere neanche di scaricarli. Purtroppo non posso fare miracoli 😅

**Comment by aleeessio** [comment]
> Ciao? Grazie di aver segnalato il problema. Se stavi provando a scaricare una preactivation (ossia anteprima, cioé che non é un libro propriamente tuo) ed é scaduta, allora il problema é sicuramente quello. A meno che non ci sia un modo per visualizzarla anche sul sito bsmart una volta scaduta, allora la risoluzione del bug sarà semplicemnte non mostrare libri scaduti, e quindi non permettere neanche di scaricarli. Purtroppo non posso fare miracoli 😅

Non so so se sia possibile in qualche modo modificare il boolean su true, dato che ora che è scaduta è su false..in qualche modo forse ce la si può fare ma io purtroppo ho conoscenze limitate. In ogni caso valuta tu, se vedi proprio che non si riesce penso sia meglio come hai detto, ovvero non mostrare direttamente le anteprime scadute. Allo stesso tempo però le anteprime visualizzabili (il periodo che bSmart consente è da fine Agosto a fine Ottobre di ogni anno) ti consiglierei di lasciare la possibilità di scaricarli, magari a qualcuno non è ancora arrivato il libro con il codice e per il momento si arrangia così. Comunque le mie sono solo idee, procedi come meglio credi :)

**Comment by FelixFrog** [comment]
Il problema rimane che se il tuo account non è autorizzato a vedere certi libri, non c'è modo di scaricarli. L'errore era dato dal fatto che anche se lo script ti mostrava il libro nell'elenco non potevi poi scaricarlo perchè non più autorizzato, restituendo un 403. La funzionalità di scaricare le anteprime rimane, ma una volta finito il periodo di autorizzazione non comprariranno più nell'elenco i libri non attivati
