### ISSUE TITLE
Takedown notice

### ISSUE THREAD

**Issue by amalferpoma** [FelixFrog/pdfgrabber#75]
Ciao Francesco,

rimuovi, per favore, questo repository da Github ed evita di pubblicare istruzioni per la rimozione del DRM dai libri digitali.
Come saprai, non è una cosa legale. Se non lo sai, benvenuto nel mondo aggiornato.
Sì, un utente ha diritto ad avere una copia per uso personale. No, non può farlo rimuovendo il DRM se l'utente può avere accesso ad una copia personale. Sì, è una violazione del copyright farlo.

Se vuoi fare un colloquio da noi, sentiamoci. Se vuoi sparire, bye bye. Se non viene rimosso questo repository: ci sentiamo presto.

**Comment by ErricoV1** [comment]
vi suggerirei di usare un linguaggio più legale per questo tipo di informazioni

**Comment by ErricoV1** [comment]
credo che lavorando alla zanichelli lei abbia diritto a far rimuovere la parte dedicata alla Zanichelli (sempre che vi abbia incaricato). altre sezioni del downloader possono essere rimosse solo da Mondadori, Palumbo Editore, Pearson o altre società.

**Comment by ErricoV1** [comment]
(non sono avvocato)

**Comment by amalferpoma** [comment]
Neanche io sono avvocato, sono sviluppatore, come voi immagino. Gli
avvocati preferisco non coinvolgerli, anche perché non credo che l'intento
fosse malevolo, ma neanche benefico.
Ben vengano le segnalazioni di falle di sicurezza, sono contento di averle
e ci spingono a lavorare meglio.
Fossi in voi tirerei giù anche le altre, ma non ho nessuna autorità per
chiedervelo, solo buon senso.

Grazie per la risposta, rimango disponibile ad incontrarvi aveste voglia di
fare due chiacchiere.

Il giorno ven 22 mar 2024 alle ore 19:10 Errico ***@***.***>
ha scritto:

> Questa è la prima volta che ricevi un'email da questo mittente. Assicurati
> che sia qualcuno di cui ti fidi.
>
> (non sono avvocato)
>
> —
> Reply to this email directly, view it on GitHub
> <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2FFelixFrog%2Fpdfgrabber%2Fissues%2F75%23issuecomment-2015648455&e=1c203a69&h=09e13fa9&f=y&p=y>,
> or unsubscribe
> <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHOS5U5YRB43UU6MHV2FWBLYZRXYBAVCNFSM6AAAAABFDASULCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMJVGY2DQNBVGU&e=1c203a69&h=4b27abeb&f=y&p=y>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>
>
> --
> Questo messaggio è stato analizzato con MAIL SICURA ed è risultato non
> infetto.
> Segnala come spam.
> <https://mailsicura.ot-mail.it/action/4V1VjZ1hdyzyNn/learn-spam>
> Mettilo in blocklist.
> <https://mailsicura.ot-mail.it/action/4V1VjZ1hdyzyNn/blocklist>
>


-- 

{ name     : "Andrea Malfer Poma",
  role     : "Direttore sviluppo applicazioni digitali",
  email    : ***@***.***",
  phone    : "+39 051 293351",
  mobile   : "+39 349 4362549",
  location : "Bologna, Italia",
  twitter  : ***@***.*** <http://twitter.com/repsah>",
  linkedin : "andreamalferpoma
<https://www.linkedin.com/in/andreamalferpoma>" }

**Comment by ErricoV1** [comment]
io non sono coinvolto nel progetto ma avevo pensato fosse una richiesta di carattere legale e quindi sentivo il bisogno di chiarificare

**Comment by ErricoV1** [comment]
questi messaggi sono aperti a tutti

**Comment by ErricoV1** [comment]
(e sono minorenne)

**Comment by CoachYT1** [comment]
Neanche io sono un avvocato ma pubblicare uno strumento per scaricare il pdf di un libro non dovrebbe essere illegale. 
Sarebbe illegale se venisse pubblicato direttamente il file pdf, non lo strumento per scaricarlo.

**Comment by stepersy** [comment]
@amalferpoma Bro, ma hai letteralmente sul tuo profilo una repo per fare la stessa identica cosa che fa questo progetto. Perché bisognerebbe bannare questo progetto se ne hai uno uguale te che (a quanto pare) lavori alla Zanichelli?

**Comment by FelixFrog** [comment]
Tutte le menzioni di Zanichelli sono state rimosse dal progetto
