### ISSUE TITLE
problemi nell'apertura dei file

### ISSUE THREAD

**Issue by SHINICI001** [FelixFrog/pdfgrabber#86]
PS C:\Users\jinji\pdfgrabber-master> py main.py
Traceback (most recent call last):
  File "C:\Users\jinji\pdfgrabber-master\main.py", line 1, in <module> 
    import utils
  File "C:\Users\jinji\pdfgrabber-master\utils.py", line 2, in <module>
    import fitz
ModuleNotFoundError: No module named 'fitz'
PS C:\Users\jinji\pdfgrabber-master>

**Comment by FelixFrog** [comment]
Ciao, non hai eseguito tutti gli step elencati nel [README.txt](https://github.com/FelixFrog/pdfgrabber?tab=readme-ov-file#installation). Devi dare in comando `pip install -r requirements.txt`
Dovrebbe funzionare, fammi sapere.

**Comment by SHINICI001** [comment]
i already done this


Il giorno mer 19 giu 2024 alle ore 19:37 Francesco Ognibene <
***@***.***> ha scritto:

**Comment by SHINICI001** [comment]
Requirement already satisfied: pymupdf in d:\python\lib\site-packages (from -r requirements.txt (line 1)) (1.23.1)
Requirement already satisfied: rich in d:\python\lib\site-packages (from -r requirements.txt (line 2)) (13.5.2)
Requirement already satisfied: requests in d:\python\lib\site-packages (from -r requirements.txt (line 3)) (2.31.0)
Requirement already satisfied: pycryptodome in d:\python\lib\site-packages (from -r requirements.txt (line 4)) (3.18.0)
Requirement already satisfied: u-msgpack-python in d:\python\lib\site-packages (from -r requirements.txt (line 5)) (2.8.0)
Requirement already satisfied: tinydb in d:\python\lib\site-packages (from -r requirements.txt (line 6)) (4.8.0)
Requirement already satisfied: playwright in d:\python\lib\site-packages (from -r requirements.txt (line 7)) (1.37.0)
Requirement already satisfied: lxml in d:\python\lib\site-packages (from -r requirements.txt (line 8)) (5.2.2)
Requirement already satisfied: PyMuPDFb==1.23.0 in d:\python\lib\site-packages (from pymupdf->-r requirements.txt (line 1)) (1.23.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in d:\python\lib\site-packages (from rich->-r requirements.txt (line 2)) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in d:\python\lib\site-packages (from rich->-r requirements.txt (line 2)) (2.16.1)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\python\lib\site-packages (from requests->-r requirements.txt (line 3)) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in d:\python\lib\site-packages (from requests->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\python\lib\site-packages (from requests->-r requirements.txt (line 3)) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in d:\python\lib\site-packages (from requests->-r requirements.txt (line 3)) (2023.7.22)
Requirement already satisfied: greenlet==2.0.2 in d:\python\lib\site-packages (from playwright->-r requirements.txt (line 7)) (2.0.2)
Requirement already satisfied: pyee==9.0.4 in d:\python\lib\site-packages (from playwright->-r requirements.txt (line 7)) (9.0.4)
Requirement already satisfied: typing-extensions in d:\python\lib\site-packages (from pyee==9.0.4->playwright->-r requirements.txt (line 7)) (4.7.1)   
Requirement already satisfied: mdurl~=0.1 in d:\python\lib\site-packages (from markdown-it-py>=2.2.0->rich->-r requirements.txt (line 2)) (0.1.2)      
PS C:\Users\jinji\pdfgrabber-master> py main.py
Traceback (most recent call last):
  File "C:\Users\jinji\pdfgrabber-master\main.py", line 1, in <module>
    import utils
  File "C:\Users\jinji\pdfgrabber-master\utils.py", line 2, in <module>
    import fitz
ModuleNotFoundError: No module named 'fitz'
PS C:\Users\jinji\pdfgrabber-master>

**Comment by FelixFrog** [comment]
Hai ragione! PyMuPDF ha cambiato nome della libreria e nelle ultime versioni `import fitz` non funziona più! Ho aggiornato i `requirements.txt` forzando l'ultima versiona prima del cambiamento come "hot fix" temporaneo. Scaricando di nuovo pdfgrabber e rieseguendo il comando dovrebbe funzionare di nuovo

**Comment by SHINICI001** [comment]
perfetto!! funziona tutto, grazie infinite !
