### ISSUE TITLE
come aggiungere il nome del libro al file pdf di output

### ISSUE THREAD

**Issue by sefirothmorpheus** [FelixFrog/pdfgrabber#87]
ciao
cosa devo modificare nei vari files in modo che il file di output abbia come nome non solo il numero del libro ma anche il titolo del libro?
grazie

**Comment by Bbalduzz** [comment]
https://github.com/FelixFrog/pdfgrabber/blob/cbe343cd7001f443316778821393d4807d401c35/utils.py#L39C2-L39C59

sostituisci: `(f"{bookid}.pdf")` con `(f"{bookid}-{data['title']}.pdf")` o come preferisci
