### ISSUE TITLE
problema su hubscuola

### ISSUE THREAD

**Issue by sefirothmorpheus** [FelixFrog/pdfgrabber#88]
primo libro
![Cattura](https://github.com/FelixFrog/pdfgrabber/assets/156643499/0b2e81ec-c995-42da-9e81-30c708fd9d2a)

secondo libro
![Cattura](https://github.com/FelixFrog/pdfgrabber/assets/156643499/1759275a-c659-4b51-8bbe-9ef1491c0277)

terzo libro
![Cattura](https://github.com/FelixFrog/pdfgrabber/assets/156643499/b927c2d3-f903-4fa7-9b24-b9994972c94e)

**Comment by Idontgivefuck** [comment]
Ciao @sefirothmorpheus

Attualmente sembrerebbe che il developer non abbia ancora effettuato un aggiornamento per risolvere questo bug. Tuttavia ho riscontrato i tuoi stessi medesimi errori e ho provveduto ad aggiornare autonomamente il file hbs.py aggiungendo delle funzioni di debug che mi hanno permesso di capire cosa succedeva quando il software incappava in quest'errore. Sembrerebbe che quando lo script va a cercare la lista degli ID dei capitoli da scaricare, trovi anche degli ID su cui non viene permesso il download dello zip file perchè semplicemente viene restituito un codice di NOT FOUND sul server Hub Scuola. Percui l'unico fix che ho potuto inserire è stato quello di skippare questi capitoli, quindi ho aggiunto una funzione che gestisce questo errore. Probabilmente sono dei capitoli "fantasma" che effettivamente non contengono pagine rilevanti anche perchè sia da quello che ho riscontrato io, sia da quello che vedo nelle tue foto sembrerebbe un errore che avviene esclusivamente nel rendering delle ultime pagine del libro, se non proprio sull'ultima pagina. Se vuoi essere sicuro che ci siano tutte le pagine confronta la versione dell'Hub Young reader con quella scaricata in modo da accertare che effettivamente ci siano tutte le pagine e fammelo sapere in modo tale che posso finalmente confermare la mia teoria che quei capitolo semplicemente sono vuoti. Prima che scoprissi questo software utilizzavo un altro metodo per scaricare libri di Hub Scuola, scaricavo su Windows l'applicazione Hub Young, mi loggavo, scaricavo al 100% il libro che volevo consultare e poi andando nella cartella C:\Users\<iltuonomeutente>\AppData\Local\HUB young.v2, trovavo una cartella con l'id corrispondente al libro e cliccando avevo delle sottocartelle che rappresentavano i vari capitoli in cui all'interno vi erano dei file PDF delle varie pagine del capitolo. Semplicemente tramite Adobe convertivo tutti quei piccoli PDF in un unico grande PDF e avevo il libro. In caso ne avessi bisogno sentiti libero anche di usare questo metodo, soprattutto se l'errore avviene durante il rendering di capitoli che poi effettivamente contengono delle pagine, che però il mio script salta (ripeto per ora avviene solo nell'ultima pagina dell'ultimo capitolo, però non si sa mai) :)
Spero di essere stato chiaro durante la spiegazione (probabilmente no), per qualsiasi altra informazione o comunque per qualsiasi altro aggiornamento per capire se questo script aggiornato funziona anche per te fammelo sapere


Ecco a te comunque il file aggiornato hbs.py (ricordati di sostituirlo con quello preesistente)
[hbs.zip](https://github.com/user-attachments/files/16015844/hbs.zip)

**Comment by ruryx00** [comment]
Ciao @Idontgivefuck 
Ho provato ad utilizzare il tuo fix ma ho ricevuto un errore (allego screenshot) spero sia solo un errore riguardate qualche modulo non aggiornato/installato. Spero che questo feedback ti possa essere utile.
![Screenshot 2024-09-16 093249](https://github.com/user-attachments/assets/b6671cae-7d8c-4e05-94b0-c9702d9cd147)

**Comment by FelixFrog** [comment]
Grazie per la segnalazione e grazie per @Idontgivefuck per averci dato un'occhiata. Se @ruryx00 o @sefirothmorpheus mi possono contattare su telegram a [t.me/fflxx](t.me/fflxx) proverò a implementare una soluzione che non rischi di scartare del contenuto valido

**Comment by ruryx00** [comment]
ciao @FelixFrog ,
ho cancellato il mio commento perché sono riuscito a far funzionare il fix su un altro computer. l'errore che avevo riscontrato probabilmente era legato al conflitto di roba nella mia installazione di python. grazie mille per il fix @Idontgivefuck

**Comment by Idontgivefuck** [comment]
> Grazie per la segnalazione e grazie per @Idontgivefuck per averci dato un'occhiata. Se @ruryx00 o @sefirothmorpheus mi possono contattare su telegram a [t.me/fflxx](t.me/fflxx) proverò a implementare una soluzione che non rischi di scartare del contenuto valido

Figurati grazie a te per i tuoi continui update a questo progetto

**Comment by Idontgivefuck** [comment]
> ciao @FelixFrog ,
> ho cancellato il mio commento perché sono riuscito a far funzionare il fix su un altro computer. l'errore che avevo riscontrato probabilmente era legato al conflitto di roba nella mia installazione di python. grazie mille per il fix @Idontgivefuck 

Sono felice che tu abbia risolto il problema

**Comment by FelixFrog** [comment]
L'ultimo commit dovrebbe aver risolto il problema. @Idontgivefuck @ruryx00 potreste confermare che il fix "ufficiale" funziona? Per ora chiudo già la issue
