### ISSUE TITLE
nuovo sistema di login sanoma (ex pearson)

### ISSUE THREAD

**Issue by damnfe** [FelixFrog/pdfgrabber#89]
il collegamento dello script alla piattaforma continua a funzionare con tanto di login (evidentemente avranno mantenuto le vecchie api) ma quando va a caricare la libreria non tiene conto dei libri attivati dopo l’update del sito, impedendone il download 

EDIT: ho trovato un workaround che permette di scaricare ugualmente i libri senza script

**Comment by Idontgivefuck** [comment]
Ho riscontrato giusto ieri lo stesso problema. Ad aggravare la situazione vi è anche il fatto che tutti i nuovi account creati con il nuovo endpoint del nuovo API sembrano risultare addirittura incorretti se si prova ad utilizzare il vecchio API che permetteva l'acquisizione del token (mi riferisco a https://login.pearson.com/v1/piapi/login/webcredentials). Ho già fatto presente tramite Telegram al developer di tutto ciò ma sto ancora aspettando una risposta.

**Comment by damnfe** [comment]
ahh ecco perché, è come se ora lo script si collegasse a un sito fantasma

**Comment by Idontgivefuck** [comment]
@damnfe sì, anch'io, letteralmente mi restituisce il libro in .PDF proprio senza fatica. Non so se è lo stesso tuo ma in caso comunque è veramente pazzesco

**Comment by damnfe** [comment]
@Idontgivefuck sì probabilmente è lo stesso, non capisco come mai ci sia dato che il sito carica i libri “alla zanichelli” con tutti gli asset delle pagine presi singolarmente

**Comment by reanto91** [comment]
@damnfe puoi dirmi di cosa si tratta? puoi indicarmi il workaround?

**Comment by Idontgivefuck** [comment]
> @damnfe puoi dirmi di cosa si tratta? puoi indicarmi il workaround?

Hai Telegram? Se sì dammi la tua @ che ti insegno come fare

**Comment by reanto91** [comment]
Ciao,
puoi scrivermi su telegram:
@brainlyL8

aspetto tuo messaggio.
Grazie

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by FelixFrog** [comment]
Ciao! Grazie a tutti delle segnalazioni. 626491618c7e9a32bcaa771a633d5afec73c346d introduce supporto a Sanoma My Place
Il tool non effettua migrazione dell'account Pearson My Place, è necessario svolgerlo autonomamente (ossia loggarsi almeno una volta con le credenziali pearson sul sito sanoma).
Come sempre fatemi presente qualunque bug abbiate riscontrato

**Comment by Idontgivefuck** [comment]
> Ciao! Grazie a tutti delle segnalazioni. [6264916](https://github.com/FelixFrog/pdfgrabber/commit/626491618c7e9a32bcaa771a633d5afec73c346d) introduce supporto a Sanoma My Place Il tool non effettua migrazione dell'account Pearson My Place, è necessario svolgerlo autonomamente (ossia loggarsi almeno una volta con le credenziali pearson sul sito sanoma). Come sempre fatemi presente qualunque bug abbiate riscontrato

Grazie tante per il tuo repentino update, lo apprezziamo molto ❤️
