### ISSUE TITLE
integrazione di young.deascuola.it

### ISSUE THREAD

**Issue by sefirothmorpheus** [FelixFrog/pdfgrabber#91]
ciao
vorrei sapere se è possibile avere l'integrazione del sistema young.deascuola.it
funziona allo stesso modo di hubscuola, ma i libri caricati sono diversi, al momento
ho provato sul tool ad usare hbs con il token di young.deascuola.it ma quando carica la libreria dice che non ci sono libri mentre ne ho 8 (come si vede dalle foto allegate)

![dea1](https://github.com/FelixFrog/pdfgrabber/assets/156643499/709abd82-383c-4f39-86ad-d3e9914e3c00)
![dea2_1](https://github.com/FelixFrog/pdfgrabber/assets/156643499/d76f9fc9-a669-4fbe-814e-c8e6db277704)
![dea3](https://github.com/FelixFrog/pdfgrabber/assets/156643499/c0005eef-357c-4fda-b19a-5e6cb0a5e4f4)

**Comment by reanto91** [comment]
Salve,
i libri di Deascuola, migreranno ufficialmente sulla piattaforma HubScuola,
a partire da settembre.
Da quella data li potrà trovare su suddetta piattaforma.

**Comment by rictech** [comment]
Ho provato oggi a scaricare un libro dal nuovo Hub Scuola e funziona tutto perfettamente!

**Comment by rictech** [comment]
Non c'è bisogno di alcun aggiustamento, è tutto a posto
