### ISSUE TITLE
Sanoma My Place - Login failed: response.message.internal_error

### ISSUE THREAD

**Issue by OnePewPew** [FelixFrog/pdfgrabber#92]
Salve,
quando inserisco le credenziali per il login a Sanoma My Place, il programma risponde con `Login failed: response.message.internal_error`

**Comment by Idontgivefuck** [comment]
Salve, ti sei assicurato di aver effettuato la migrazione dell'account da Pearson a Sanona? Per farlo basta effettuare l'accesso su https://sanoma.it/place?hsLang=it e seguire la procedura guidata. In caso l'avessi già effettuata potrebbe essere un problema dell'endpoint

**Comment by OnePewPew** [comment]
Grazie per il riscontro repentino. Attraverso il link fornito ho inserito, per accedere, l’username che ho usato per creare l’account Pearson e risulta che io abbia già effettuato la migrazione.

**Comment by Idontgivefuck** [comment]
Purtroppo non so come aiutarti poichè personalmente il servizio funziona alla grande. Assicurati di mettere nel campo dell'username tutta l'email senza lasciare spazi vuoti e controlla di immettere la password correttamente (modifica la linea 102 del file main.py togliendo "password=True", così puoi visualizzare la password in plain text e sei sicuro di star inserendo la password corretta)

Altrimenti potresti recuperare l'access token e reflesh token manualmente e poi immetterli nel software (ricordali di separarli da una |)

**Comment by FelixFrog** [comment]
Può essere che ci siano altri meccanismi di login che pdfgrabber non è ancora in grado di gestire. Potresti provare a scaricare l'app di Sanoma per dispositivi mobili (Sanoma My Digital Library o una cosa del genere) e fare il login lì prima di riprovare su pdfgrabber. Se non dovesse funzionare contattami su [telegram](t.me/fflxx)

**Comment by OnePewPew** [comment]
Il problema è stato risolto quando ho cambiato la password e forse il problema è legato ad alcuni caratteri che erano contenuti in essa. In ogni caso adesso il programma funziona correttamente.
Grazie per il supporto fornito

**Comment by FelixFrog** [comment]
Bene. Potrebbe essere un bug di pdfgrabber e dell'encoding della password quando viene inviata al server. In ogni caso chiudo la issue; se dovesse ripresentarsi il problema saprò dove guardare.
