### ISSUE TITLE
[Feature Request] Classoos service

### ISSUE THREAD

**Issue by Shuggy999** [FelixFrog/pdfgrabber#95]
Hello there,
I was wondering if you have any plan to support classoos, another service with Apryse WebViewer drm like BlinkLearning. There are free books on the service from Project Gutenberg, but also one day trials of any book.

If you could provide information on how to crack this DRM, or to start how to download the  entire encrypted pdf as it has the 'range' set to a value in order to only download one part at a time.

Thanks a lot. 

---

Buongiorno,
Mi chiedevo se hai intenzione di supportare 'classoos', un altro servizio con Apryse WebViewer DRM come BlinkLearning. Ci sono libri gratuiti sul servizio di Project Gutenberg, ma anche prove di un giorno di qualsiasi libro.

Se potessi fornire informazioni su come decifrare questo DRM o su come iniziare a scaricare l'intero pdf crittografato poiché ha il "range" impostato su un valore per scaricare solo una parte alla volta.

Grazie mille.

**Comment by Shuggy999** [comment]
EDIT: I have wrote my own script and plan to make it into a service myself

**Comment by FelixFrog** [comment]
Non avendo accesso alla piattaforma non so se è effettivamente così ma potrebbe essere che sia un'istanza dello stesso software su un dominio diverso (come ad esempio mcmillan e blinkenlearning). In quel caso aggiungere il supporto è molto facile

**Comment by Shuggy999** [comment]
ciao,
l'account è gratuito e ci sono libri di pubblico dominio gratuiti da provare. Non sono sicuro di come funzionano i servizi, ma condividerò il mio script. Utilizza alcuni strumenti extra, perché i pdf hanno qualcosa al loro interno che li rompe.

Lo script vede la libreria e scarica tutti i libri non scaricati.
scusa per il pessimo italiano, sono straniero
