### ISSUE TITLE
Errore durante download da Sanoma

### ISSUE THREAD

**Issue by tonyiron83** [FelixFrog/pdfgrabber#96]
<img width="695" alt="image" src="https://github.com/user-attachments/assets/5bfb4529-7b28-4a69-87ae-8eb6810e8a27">

Si segnala errore durante il download da sanoma.

**Comment by emcpteam** [comment]
Ciao confermo l'errore su download da libri da sanoma.
![Screenshot 2024-09-12 alle 18 19 18](https://github.com/user-attachments/assets/925cf14c-a50d-45fe-a5c9-7d942471b10b)
