### ISSUE TITLE
Rendering error on a single Bsmart Ebook

### ISSUE THREAD

**Issue by RiccardoWilliam** [FelixFrog/pdfgrabber#97]
Ho attivato un libro su bsmart e se accedo al web viewer non trovo ovviamente alcun problema con la lettura. Ho provato a scaricarlo ma dopo aver aperto il pdf mi sono accorto che molte pagine sono renderizzate male. Allego immagini.
![Screenshot 2024-09-12 161209](https://github.com/user-attachments/assets/ec3004fd-b798-4cca-8b72-948cd0518629)
Screenshot del web viewer
![Screenshot 2024-09-12 161315](https://github.com/user-attachments/assets/15e9a69c-b837-4927-ae1f-70aa9b733c3f)
screenshot del pdf scaricato

molte altre pagine sono renderizzate come mostrato nella seconda immagine

**Comment by FelixFrog** [comment]
Nel tuo file config.ini prova a impostare EzSave = no e Compress = no e a riscaricare un libro che ti da problemi. Se è un problema della libreria pymupdf dovrebbe questo dovrebbe risolvere il problema. Fammi sapere il risultato

**Comment by RiccardoWilliam** [comment]
Grazie! Ha funzionato, non mi sembra ci siano altri errori di rendering.
