### ISSUE TITLE
pmb service error "no books"

### ISSUE THREAD

**Issue by ruryx00** [FelixFrog/pdfgrabber#99]
Ho tentato di scaricare i libri dalla piattaforma palumbo editore, in seguito alla selezione dell'editore ricevo l'errore "no books" (screenshot allegato). 
![image](https://github.com/user-attachments/assets/f587e0dc-478f-4727-85cc-34540f55b5f9)
Ho aperto la piattaforma a cui si collega lo script e provando ad aprire uno dei libri esce il seguente messaggio:
![image](https://github.com/user-attachments/assets/f138fc3f-c8be-4114-b91e-26a4b5220162)
Avete già riscontrato lo stesso problema o dovrò aspettare il mese di gennaio come dice sul sito?
Grazie in anticipo per il supporto.

**Comment by FelixFrog** [comment]
Purtroppo pdfgrabber funziona come dovrebbe. I libri sono accessibili solo da gennaio a maggio, non ho (ancora) trovato modi per bypassare questa limitazione dato che i link ai libri non sono accessibili in questo momento. Si potrebbero comunque scaricare tutti i libri ogni anno in modo che manchino solo quelli nuovi, ma farlo sta a voi utenti, io vi do solo gli strumenti ;-)
